import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
  output: 'export', // Required for Tauri static export
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.externals = config.externals || [];
      config.externals.push({
        '@tauri-apps/api/fs': 'commonjs @tauri-apps/api/fs',
        '@tauri-apps/api/path': 'commonjs @tauri-apps/api/path',
        '@tauri-apps/api/dialog': 'commonjs @tauri-apps/api/dialog',
        '@tauri-apps/api/shell': 'commonjs @tauri-apps/api/shell',
        '@tauri-apps/api/window': 'commonjs @tauri-apps/api/window',
        '@tauri-apps/api/event': 'commonjs @tauri-apps/api/event',
        '@tauri-apps/api/process': 'commonjs @tauri-apps/api/process',
        '@tauri-apps/api/rpc': 'commonjs @tauri-apps/api/rpc',
        '@tauri-apps/api/clipboard': 'commonjs @tauri-apps/api/clipboard',
        '@tauri-apps/api/notification': 'commonjs @tauri-apps/api/notification',
        '@tauri-apps/api/protocol': 'commonjs @tauri-apps/api/protocol',
        '@tauri-apps/api/global-shortcut': 'commonjs @tauri-apps/api/global-shortcut',
        '@tauri-apps/api/http': 'commonjs @tauri-apps/api/http',
        '@tauri-apps/api/os': 'commonjs @tauri-apps/api/os',
        '@tauri-apps/api/cli': 'commonjs @tauri-apps/api/cli',
        '@tauri-apps/api/updater': 'commonjs @tauri-apps/api/updater',
        '@tauri-apps/api/webview': 'commonjs @tauri-apps/api/webview',
        '@tauri-apps/api/app': 'commonjs @tauri-apps/api/app',
        '@tauri-apps/api/menu': 'commonjs @tauri-apps/api/menu',
        '@tauri-apps/api/tray': 'commonjs @tauri-apps/api/tray',
        '@tauri-apps/api/url': 'commonjs @tauri-apps/api/url',
        '@tauri-apps/api/window-state': 'commonjs @tauri-apps/api/window-state',
        '@tauri-apps/api/fs/watch': 'commonjs @tauri-apps/api/fs/watch',
        '@tauri-apps/api/fs/readDir': 'commonjs @tauri-apps/api/fs/readDir',
        '@tauri-apps/api/fs/readFile': 'commonjs @tauri-apps/api/fs/readFile',
        '@tauri-apps/api/fs/writeFile': 'commonjs @tauri-apps/api/fs/writeFile',
        '@tauri-apps/api/fs/removeDir': 'commonjs @tauri-apps/api/fs/removeDir',
        '@tauri-apps/api/fs/removeFile': 'commonjs @tauri-apps/api/fs/removeFile',
        '@tauri-apps/api/fs/rename': 'commonjs @tauri-apps/api/fs/rename',
        '@tauri-apps/api/fs/copyFile': 'commonjs @tauri-apps/api/fs/copyFile',
        '@tauri-apps/api/fs/exists': 'commonjs @tauri-apps/api/fs/exists',
        '@tauri-apps/api/fs/createDir': 'commonjs @tauri-apps/api/fs/createDir',
        '@tauri-apps/api/fs/writeBinaryFile': 'commonjs @tauri-apps/api/fs/writeBinaryFile',
        '@tauri-apps/api/fs/readBinaryFile': 'commonjs @tauri-apps/api/fs/readBinaryFile',
        '@tauri-apps/api/path/appDir': 'commonjs @tauri-apps/api/path/appDir',
        '@tauri-apps/api/path/appDataDir': 'commonjs @tauri-apps/api/path/appDataDir',
        '@tauri-apps/api/path/appLocalDataDir': 'commonjs @tauri-apps/api/path/appLocalDataDir',
        '@tauri-apps/api/path/appCacheDir': 'commonjs @tauri-apps/api/path/appCacheDir',
        '@tauri-apps/api/path/appConfigDir': 'commonjs @tauri-apps/api/path/appConfigDir',
        '@tauri-apps/api/path/appLogDir': 'commonjs @tauri-apps/api/path/appLogDir',
        '@tauri-apps/api/path/audioDir': 'commonjs @tauri-apps/api/path/audioDir',
        '@tauri-apps/api/path/cacheDir': 'commonjs @tauri-apps/api/path/cacheDir',
        '@tauri-apps/api/path/configDir': 'commonjs @tauri-apps/api/path/configDir',
        '@tauri-apps/api/path/dataDir': 'commonjs @tauri-apps/api/path/dataDir',
        '@tauri-apps/api/path/desktopDir': 'commonjs @tauri-apps/api/path/desktopDir',
        '@tauri-apps/api/path/documentDir': 'commonjs @tauri-apps/api/path/documentDir',
        '@tauri-apps/api/path/downloadDir': 'commonjs @tauri-apps/api/path/downloadDir',
        '@tauri-apps/api/path/executableDir': 'commonjs @tauri-apps/api/path/executableDir',
        '@tauri-apps/api/path/fontDir': 'commonjs @tauri-apps/api/path/fontDir',
        '@tauri-apps/api/path/homeDir': 'commonjs @tauri-apps/api/path/homeDir',
        '@tauri-apps/api/path/localDataDir': 'commonjs @tauri-apps/api/path/localDataDir',
        '@tauri-apps/api/path/pictureDir': 'commonjs @tauri-apps/api/path/pictureDir',
        '@tauri-apps/api/path/publicDir': 'commonjs @tauri-apps/api/path/publicDir',
        '@tauri-apps/api/path/resourceDir': 'commonjs @tauri-apps/api/path/resourceDir',
        '@tauri-apps/api/path/runtimeDir': 'commonjs @tauri-apps/api/path/runtimeDir',
        '@tauri-apps/api/path/templateDir': 'commonjs @tauri-apps/api/path/templateDir',
        '@tauri-apps/api/path/videoDir': 'commonjs @tauri-apps/api/path/videoDir',
        '@tauri-apps/api/path/tempDir': 'commonjs @tauri-apps/api/path/tempDir',
        '@tauri-apps/api/path/join': 'commonjs @tauri-apps/api/path/join',
        '@tauri-apps/api/path/normalize': 'commonjs @tauri-apps/api/path/normalize',
        '@tauri-apps/api/path/dirname': 'commonjs @tauri-apps/api/path/dirname',
        '@tauri-apps/api/path/extname': 'commonjs @tauri-apps/api/path/extname',
        '@tauri-apps/api/path/basename': 'commonjs @tauri-apps/api/path/basename',
        '@tauri-apps/api/path/isAbsolute': 'commonjs @tauri-apps/api/path/isAbsolute',
        '@tauri-apps/api/path/relative': 'commonjs @tauri-apps/api/path/relative',
        '@tauri-apps/api/path/from': 'commonjs @tauri-apps/api/path/from',
        '@tauri-apps/api/path/to': 'commonjs @tauri-apps/api/path/to',
        '@tauri-apps/api/path/resolve': 'commonjs @tauri-apps/api/path/resolve',
        '@tauri-apps/api/path/sep': 'commonjs @tauri-apps/api/path/sep',
        '@tauri-apps/api/dialog/open': 'commonjs @tauri-apps/api/dialog/open',
        '@tauri-apps/api/dialog/save': 'commonjs @tauri-apps/api/dialog/save',
        '@tauri-apps/api/shell/execute': 'commonjs @tauri-apps/api/shell/execute',
        '@tauri-apps/api/shell/spawn': 'commonjs @tauri-apps/api/shell/spawn',
        '@tauri-apps/api/shell/Command': 'commonjs @tauri-apps/api/shell/Command',
        '@tauri-apps/api/shell/open': 'commonjs @tauri-apps/api/shell/open',
        '@tauri-apps/api/window/WebviewWindow': 'commonjs @tauri-apps/api/window/WebviewWindow',
        '@tauri-apps/api/window/getCurrent': 'commonjs @tauri-apps/api/window/getCurrent',
        '@tauri-apps/api/window/getAll': 'commonjs @tauri-apps/api/window/getAll',
        '@tauri-apps/api/window/availableMonitors': 'commonjs @tauri-apps/api/window/availableMonitors',
        '@tauri-apps/api/window/currentMonitor': 'commonjs @tauri-apps/api/window/currentMonitor',
        '@tauri-apps/api/window/primaryMonitor': 'commonjs @tauri-apps/api/window/primaryMonitor',
        '@tauri-apps/api/window/open': 'commonjs @tauri-apps/api/window/open',
        '@tauri-apps/api/event/listen': 'commonjs @tauri-apps/api/event/listen',
        '@tauri-apps/api/event/emit': 'commonjs @tauri-apps/api/event/emit',
        '@tauri-apps/api/process/exit': 'commonjs @tauri-apps/api/process/exit',
        '@tauri-apps/api/process/relaunch': 'commonjs @tauri-apps/api/process/relaunch',
        '@tauri-apps/api/process/currentWorkingDirectory': 'commonjs @tauri-apps/api/process/currentWorkingDirectory',
        '@tauri-apps/api/process/command': 'commonjs @tauri-apps/api/process/command',
        '@tauri-apps/api/rpc/invoke': 'commonjs @tauri-apps/api/rpc/invoke',
        '@tauri-apps/api/clipboard/readText': 'commonjs @tauri-apps/api/clipboard/readText',
        '@tauri-apps/api/clipboard/writeText': 'commonjs @tauri-apps/api/clipboard/writeText',
        '@tauri-apps/api/notification/requestPermission': 'commonjs @tauri-apps/api/notification/requestPermission',
        '@tauri-apps/api/notification/sendNotification': 'commonjs @tauri-apps/api/notification/sendNotification',
        '@tauri-apps/api/notification/isPermissionGranted': 'commonjs @tauri-apps/api/notification/isPermissionGranted',
        '@tauri-apps/api/protocol/asset': 'commonjs @tauri-apps/api/protocol/asset',
        '@tauri-apps/api/global-shortcut/register': 'commonjs @tauri-apps/api/global-shortcut/register',
        '@tauri-apps/api/global-shortcut/unregister': 'commonjs @tauri-apps/api/global-shortcut/unregister',
        '@tauri-apps/api/global-shortcut/unregisterAll': 'commonjs @tauri-apps/api/global-shortcut/unregisterAll',
        '@tauri-apps/api/global-shortcut/isRegistered': 'commonjs @tauri-apps/api/global-shortcut/isRegistered',
        '@tauri-apps/api/http/fetch': 'commonjs @tauri-apps/api/http/fetch',
        '@tauri-apps/api/http/getClient': 'commonjs @tauri-apps/api/http/getClient',
        '@tauri-apps/api/os/platform': 'commonjs @tauri-apps/api/os/platform',
        '@tauri-apps/api/os/version': 'commonjs @tauri-apps/api/os/version',
        '@tauri-apps/api/os/type': 'commonjs @tauri-apps/api/os/type',
        '@tauri-apps/api/os/arch': 'commonjs @tauri-apps/api/os/arch',
        '@tauri-apps/api/os/family': 'commonjs @tauri-apps/api/os/family',
        '@tauri-apps/api/os/hostname': 'commonjs @tauri-apps/api/os/hostname',
        '@tauri-apps/api/os/uptime': 'commonjs @tauri-apps/api/os/uptime',
        '@tauri-apps/api/os/availableParallelism': 'commonjs @tauri-apps/api/os/availableParallelism',
        '@tauri-apps/api/cli/getMatches': 'commonjs @tauri-apps/api/cli/getMatches',
        '@tauri-apps/api/updater/checkUpdate': 'commonjs @tauri-apps/api/updater/checkUpdate',
        '@tauri-apps/api/updater/installUpdate': 'commonjs @tauri-apps/api/updater/installUpdate',
        '@tauri-apps/api/updater/onUpdaterEvent': 'commonjs @tauri-apps/api/updater/onUpdaterEvent',
        '@tauri-apps/api/webview/createWebviewWindow': 'commonjs @tauri-apps/api/webview/createWebviewWindow',
        '@tauri-apps/api/app/getName': 'commonjs @tauri-apps/api/app/getName',
        '@tauri-apps/api/app/getVersion': 'commonjs @tauri-apps/api/app/getVersion',
        '@tauri-apps/api/app/getTauriVersion': 'commonjs @tauri-apps/api/app/getTauriVersion',
        '@tauri-apps/api/app/hide': 'commonjs @tauri-apps/api/app/hide',
        '@tauri-apps/api/app/show': 'commonjs @tauri-apps/api/app/show',
        '@tauri-apps/api/app/is and': 'commonjs @tauri-apps/api/app/is and',
        '@tauri-apps/api/menu/Menu': 'commonjs @tauri-apps/api/menu/Menu',
        '@tauri-apps/api/menu/MenuItem': 'commonjs @tauri-apps/api/menu/MenuItem',
        '@tauri-apps/api/menu/Submenu': 'commonjs @tauri-apps/api/menu/Submenu',
        '@tauri-apps/api/tray/TrayIcon': 'commonjs @tauri-apps/api/tray/TrayIcon',
        '@tauri-apps/api/url/open': 'commonjs @tauri-apps/api/url/open',
        '@tauri-apps/api/window-state/saveWindowState': 'commonjs @tauri-apps/api/window-state/saveWindowState',
        '@tauri-apps/api/window-state/restoreWindowState': 'commonjs @tauri-apps/api/window-state/restoreWindowState',
      });
    }
    return config;
  },
};

export default nextConfig;
